version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
